import { useEffect, useState } from "react";
import StatCard from "../components/StatCard";
import api from "../services/api";

function TodayPlanPage() {
  const [plan, setPlan] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    const loadPlan = async () => {
      try {
        const { data } = await api.get("/api/plan/today");
        setPlan(data);
      } catch (err) {
        setError(err.response?.data?.message || "Failed to load today's plan");
      }
    };

    loadPlan();
  }, []);

  return (
    <section className="grid" style={{ gap: 16 }}>
      <article className="page-card">
        <h2 className="page-title">TODAY'S PLAN</h2>
        <p className="page-subtitle">Generated by urgency ranking and your daily time limit.</p>

        <div className="grid cards">
          <StatCard label="Total allocated" value={`${plan?.totalAllocated ?? 0} min`} />
          <StatCard label="Daily limit" value={`${plan?.dailyLimit ?? 0} min`} />
          <StatCard label="Readiness score" value={`${plan?.readinessScore ?? 0}%`} />
        </div>
      </article>

      <article className="page-card">
        <h3 className="section-title">Execution list</h3>

        {plan?.items?.length ? (
          <ul className="list">
            {plan.items.map((item) => (
              <li key={item.userSkillId} className="list-item">
                <div>
                  <strong>{item.skill}</strong>
                  <p className="page-subtitle" style={{ margin: 0 }}>
                    Urgency {item.urgency}
                  </p>
                </div>
                <span className="tag brand">{item.minutes} min</span>
              </li>
            ))}
          </ul>
        ) : (
          <p className="empty">No skills allocated yet. Add role skills and practice logs.</p>
        )}

        {error ? <p className="error-text">{error}</p> : null}
      </article>
    </section>
  );
}

export default TodayPlanPage;
